(()=>{
"use strict";

const API_URL="https://script.google.com/macros/s/AKfycbzVmjLNsjRTSo6o3gtuGn_3pODvQ35ZQAluMyHZPJw1o_Xi4x4ERWRnNM0tJdY_Hm/exec";
const ADMIN_USER="TrainTraffic";
const ADMIN_PASSWORD_SHA256="c75b445cbff8e87cf1a4432649b5b91e5002a10be8e3ba573179753ddc833959";
const C={id:"ID",tanggal:"Tanggal",jam:"Jam",noKa:"No KA",relasi:"Relasi",trainset:"Trainset",sf:"SF",posisi:"Posisi Kereta",lokasi:"Lokasi",kategori:"Kategori Gangguan",uraian:"Uraian Gangguan",tindakan:"Tindakan",dampak:"Dampak",telat:"Keterlambatan",dipo:"Dipo",pelapor:"Pelapor",status:"Status",dibuat:"Waktu Input"};
const KATEGORI=["Propulsi / Traksi","Pengereman","Pintu Otomatis","Pantograf","Kelistrikan Auxiliary","Kelistrikan / Tegangan","Baterai / Charger","Bogie & Roda","Suspensi","Kopling / Coupler","Pendingin Udara","Sistem Kontrol / Monitoring","TCMS","Mikroprosesor / Kontrol","Interior & Fasilitas","Lampu","Kaca & Bodi","Pintu Kabin","Announcer / PIS","Radio / Komunikasi","Wiper","Sistem Informasi","Peralatan Keselamatan","Peralatan Darurat","Kebocoran","Asap / Bau","Overheat","Gangguan Mekanik","Gangguan Elektrik","Lain-lain"];
const DAMPAK=["Lanjut operasi","Kecepatan dibatasi","Sarana diganti","KA batal","Masuk dipo","Masuk balai yasa"];
const DIPO=["Depok","Bogor","Bukit Duri","Bekasi","Cikarang","Balai Yasa Manggarai"];
let currentUser="",userRole="",DATA=[],sunting=null,posisiPilih=null,clockTimer=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const toast=msg=>{const p=$("#pesan");if(!p)return;p.textContent=msg;p.classList.add("tampil");clearTimeout(toast.t);toast.t=setTimeout(()=>p.classList.remove("tampil"),3000)};

async function sha256(text){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function saveSession(){sessionStorage.setItem("gssession",JSON.stringify({user:currentUser,role:userRole}))}
function loadSession(){try{const s=JSON.parse(sessionStorage.getItem("gssession")||"null");if(s&&s.user&&s.role){currentUser=s.user;userRole=s.role;return true}}catch{}return false}
function clearSession(){sessionStorage.removeItem("gssession")}
function setRoleUI(){const ur=$("#userRole"),sn=$("#sidebarUserName"),sr=$("#sidebarUserRole"),bb=$("#btnBaru"),bs=$("#btnSimpan"),bh=$("#btnHapus"),bd=$("#btnBaruDb"),csv=$("#btnDbCsv");if(ur)ur.textContent=(userRole==="admin"?"Admin: ":"User: ")+currentUser;if(sn)sn.textContent=currentUser;if(sr)sr.textContent=userRole==="admin"?"Admin":"User";if(bb)bb.style.display="block";if(bs)bs.style.display="block";if(bd)bd.style.display="block";if(bh)bh.style.display="none";if(csv)csv.style.display=userRole==="admin"?"inline-flex":"none"}
function showLogin(){const a=$("#loginScreen"),b=$("#dashboardScreen");if(a)a.classList.remove("hidden");if(b)b.classList.remove("visible")}
function showDashboard(){const a=$("#loginScreen"),b=$("#dashboardScreen");if(a)a.classList.add("hidden");if(b)b.classList.add("visible");setRoleUI();if(!clockTimer){detakJam();clockTimer=setInterval(detakJam,1000)}muatData(true)}
function loginScreenInit(){const pa=$("#passwordField"),lab=$("#label1"),ra=$("#roleAdmin"),ru=$("#roleUser");ra?.addEventListener("change",()=>{if(lab)lab.textContent="Username";if(pa)pa.style.display="block"});ru?.addEventListener("change",()=>{if(lab)lab.textContent="Nama Pengguna";if(pa)pa.style.display="none";const p=$("#password");if(p)p.value=""});$("#loginBtn")?.addEventListener("click",login);$("#logoutBtn")?.addEventListener("click",logout)}
async function login(){const role=document.querySelector('input[name="role"]:checked')?.value||"user",name=$("#username")?.value.trim()||"",pass=$("#password")?.value||"",err=$("#loginError");if(err){err.style.display="none";err.textContent=""}if(!name){if(err){err.textContent=role==="admin"?"Silakan isi username":"Silakan isi nama pengguna";err.style.display="block"}return}if(role==="admin"){const h=await sha256(pass);if(name!==ADMIN_USER||h!==ADMIN_PASSWORD_SHA256){if(err){err.textContent="Username atau password salah";err.style.display="block"}return}}currentUser=name;userRole=role;saveSession();showDashboard()}
function logout(){currentUser="";userRole="";DATA=[];sunting=null;clearSession();const u=$("#username"),p=$("#password"),ra=$("#roleAdmin"),pa=$("#passwordField");if(u)u.value="";if(p)p.value="";if(ra)ra.checked=true;if(pa)pa.style.display="block";showLogin()}
function detakJam(){const d=new Date(),pad=n=>String(n).padStart(2,"0"),h=["Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"],m=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];const j=$("#jamNow"),t=$("#tglNow");if(j)j.textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;if(t)t.textContent=`${h[d.getDay()]}, ${d.getDate()} ${m[d.getMonth()]} ${d.getFullYear()}`}
function populate(){const fill=(id,arr,first)=>{const s=$(id);if(!s)return;s.innerHTML=`<option value="">${first}</option>`+arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")};fill("#iKategori",KATEGORI,"Pilih kategori");fill("#iDipo",DIPO,"Pilih dipo");fill("#iDampak",DAMPAK,"Pilih dampak");ensureStrip();ensureOtherCategory()}
function ensureOtherCategory(){const s=$("#iKategori");if(!s||$("#iKategoriLain"))return;const i=document.createElement("input");i.id="iKategoriLain";i.placeholder="Tulis singkat, mis. lampu kabin";i.style.cssText="display:none;margin-top:6px;width:100%;padding:8px 10px;border:1px solid #C9CFD9;border-radius:7px";s.parentElement.appendChild(i);s.addEventListener("change",()=>{i.style.display=s.value==="Lain-lain"?"block":"none";if(s.value!=="Lain-lain")i.value=""})}
function ensureStrip(){const s=$("#iSf");if(!s)return;s.addEventListener("change",renderStrip);renderStrip()}
function renderStrip(){const s=$("#iSf"),box=$("#stripForm");if(!s||!box)return;const n=parseInt(s.value,10)||8;if(posisiPilih>n)posisiPilih=null;box.innerHTML='<span class="arah">◀ 1</span>'+Array.from({length:n},(_,k)=>{const i=k+1;return `<span class="k${i===posisiPilih?' aktif':''}" role="button" tabindex="0" data-pos="${i}">${i}</span>`}).join("")+`<span class="arah">${n} ▶</span>`;box.querySelectorAll(".k").forEach(k=>{const pick=()=>{posisiPilih=Number(k.dataset.pos);renderStrip()};k.addEventListener("click",pick);k.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();pick()}})})}
function packMeta(d){return "__META__"+JSON.stringify({tindakan:d[C.tindakan]||"",telat:d[C.telat]||0,dipo:d[C.dipo]||"",pelapor:d[C.pelapor]||"",status:d[C.status]||"Terbuka",dibuat:d[C.dibuat]||new Date().toISOString()})}
function fromApi(r){let m={};try{const x=String(r.keterangan||r.Keterangan||"");if(x.startsWith("__META__"))m=JSON.parse(x.slice(8))}catch{}const n=Number(r.rowIndex||0);return{[C.id]:"gs-"+n,[C.tanggal]:r.Tanggal||"",[C.jam]:r.Jam||"",[C.noKa]:r["No KA"]||"",[C.relasi]:r.Relasi||"",[C.trainset]:r.Trainset||"",[C.sf]:r.SF||"",[C.posisi]:r["Posisi Kereta"]||"",[C.lokasi]:r.Lokasi||"",[C.kategori]:r.kategori_gangguan||r["Kategori Gangguan"]||"",[C.uraian]:r.uraian_gangguan||r["Uraian Gangguan"]||"",[C.tindakan]:m.tindakan||"",[C.dampak]:r.dampak||r.Dampak||"",[C.telat]:m.telat||0,[C.dipo]:m.dipo||"",[C.pelapor]:m.pelapor||"",[C.status]:m.status||"Terbuka",[C.dibuat]:m.dibuat||"",_rowIndex:n}}
async function apiRead(){const u=API_URL+"?action=read&_="+Date.now();const r=await fetch(u,{method:"GET",mode:"cors",cache:"no-store",redirect:"follow"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function apiWrite(params){const u=API_URL+"?"+new URLSearchParams(params).toString();try{await fetch(u,{method:"GET",mode:"no-cors",cache:"no-store",redirect:"follow"});return true}catch(e){throw new Error("Failed to send request to Google Sheets")}}
async function muatData(silent=false){try{const r=await apiRead();if(!r.success)throw new Error(r.error||"Gagal membaca Google Sheets");DATA=(r.data||[]).map(fromApi);sessionStorage.setItem("gsdata",JSON.stringify(DATA));renderAll();if(!silent)toast("Data berhasil dimuat")}catch(e){console.error(e);try{DATA=JSON.parse(sessionStorage.getItem("gsdata")||"[]")}catch{DATA=[]}renderAll();toast(DATA.length?"Google Sheets tidak dapat dibaca; menampilkan cache terakhir":"Data Google Sheets gagal dibaca: "+e.message)}}
function readForm(){let kat=$("#iKategori")?.value||"";if(kat==="Lain-lain"){const o=$("#iKategoriLain")?.value.trim()||"";kat=o?`Lain-lain: ${o}`:"Lain-lain"}return{[C.tanggal]:$("#iTanggal")?.value||"",[C.jam]:$("#iJam")?.value||"",[C.noKa]:$("#iNoKa")?.value.trim()||"",[C.relasi]:$("#iRelasi")?.value.trim()||"",[C.trainset]:$("#iTrainset")?.value.trim()||"",[C.sf]:$("#iSf")?.value||"8",[C.posisi]:posisiPilih||"",[C.lokasi]:$("#iLokasi")?.value.trim()||"",[C.kategori]:kat,[C.uraian]:$("#iUraian")?.value.trim()||"",[C.tindakan]:$("#iTindakan")?.value.trim()||"",[C.dampak]:$("#iDampak")?.value||"",[C.telat]:$("#iTelat")?.value||0,[C.dipo]:$("#iDipo")?.value||"",[C.pelapor]:$("#iPelapor")?.value.trim()||currentUser,[C.status]:$("#iStatus")?.value||"Terbuka",[C.dibuat]:new Date().toISOString()}}
async function simpan(){const d=readForm();if(!d[C.tanggal]||!d[C.noKa]||!d[C.trainset]||!d[C.kategori]){toast("Lengkapi tanggal, No KA, trainset, dan kategori");return}if(sunting&&userRole!=="admin"){toast("User hanya dapat membuat laporan baru");return}try{if(sunting){const r=DATA.find(x=>x[C.id]===sunting);if(!r)throw new Error("Data tidak ditemukan");await apiWrite({action:"update",rowIndex:r._rowIndex,kategori_gangguan:d[C.kategori],uraian_gangguan:d[C.uraian],dampak:d[C.dampak],keterangan:packMeta(d)})}else{await apiWrite({action:"create",tanggal:d[C.tanggal],jam:d[C.jam],no_ka:d[C.noKa],relasi:d[C.relasi],trainset:d[C.trainset],sf:d[C.sf],posisi_kereta:d[C.posisi],lokasi:d[C.lokasi],kategori_gangguan:d[C.kategori],uraian_gangguan:d[C.uraian],dampak:d[C.dampak],keterangan:packMeta(d)})}closeDrawer();toast("Permintaan simpan dikirim ke Google Sheets");setTimeout(()=>muatData(true),800)}catch(e){console.error(e);toast(e.message)}}
async function hapus(r){if(userRole!=="admin"||!r)return;if(!confirm("Hapus laporan ini?"))return;try{await apiWrite({action:"delete",rowIndex:r._rowIndex});toast("Permintaan hapus dikirim");setTimeout(()=>muatData(true),800)}catch(e){toast(e.message)}}
function openDrawer(r=null){sunting=r?r[C.id]:null;populate();const now=new Date();const set=(id,v)=>{const x=$(id);if(x)x.value=v??""};if(r){set("#iTanggal",r[C.tanggal]);set("#iJam",r[C.jam]);set("#iNoKa",r[C.noKa]);set("#iRelasi",r[C.relasi]);set("#iTrainset",r[C.trainset]);set("#iSf",r[C.sf]||8);set("#iLokasi",r[C.lokasi]);set("#iDampak",r[C.dampak]);set("#iTelat",r[C.telat]||0);set("#iDipo",r[C.dipo]);set("#iStatus",r[C.status]||"Terbuka");set("#iPelapor",r[C.pelapor]);set("#iUraian",r[C.uraian]);set("#iTindakan",r[C.tindakan]);$("#iKategori").value=r[C.kategori].startsWith("Lain-lain:")?"Lain-lain":r[C.kategori];const oi=$("#iKategoriLain");if(oi){oi.value=r[C.kategori].startsWith("Lain-lain:")?r[C.kategori].slice(10).trim():"";oi.style.display=$("#iKategori").value==="Lain-lain"?"block":"none"}posisiPilih=parseInt(r[C.posisi],10)||null}else{set("#iTanggal",now.toISOString().slice(0,10));set("#iJam",`${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}`);["#iNoKa","#iRelasi","#iTrainset","#iLokasi","#iUraian","#iTindakan"].forEach(id=>set(id,""));set("#iSf","8");set("#iTelat","0");set("#iStatus","Terbuka");set("#iPelapor",currentUser);$("#iKategori").value="";posisiPilih=null}renderStrip();$("#laciJudul").textContent=r?"Edit laporan gangguan":"Laporan gangguan baru";$("#btnHapus").style.display=r&&userRole==="admin"?"inline-flex":"none";$("#btnSimpan").style.display="inline-flex";$("#laci").classList.add("buka");$("#tirai").classList.add("buka")}
function closeDrawer(){$("#laci")?.classList.remove("buka");$("#tirai")?.classList.remove("buka");sunting=null}
function rowsFilter(){const q=$("#fCari")?.value.toLowerCase()||"",st=$("#fStatus")?.value||"",kat=$("#fKategori")?.value||"",dp=$("#fDipo")?.value||"";return DATA.filter(r=>(!st||r[C.status]===st)&&(!kat||String(r[C.kategori]).split(":")[0]===kat)&&(!dp||r[C.dipo]===dp)&&(!q||Object.values(r).join(" ").toLowerCase().includes(q)))}
function renderAll(){const rows=rowsFilter();const set=id=>$(id);set("#sTotal")?.textContent=rows.length;set("#sOpen")?.textContent=rows.filter(r=>r[C.status]!=="Selesai").length;set("#sMenit")?.textContent=rows.reduce((a,r)=>a+(Number(r[C.telat])||0),0);set("#sSet")?.textContent=new Set(rows.map(r=>r[C.trainset]).filter(Boolean)).size;set("#countLabel")?.textContent=`${rows.length} rekaman`;set("#tbody").innerHTML=rows.slice(0,50).map(r=>`<tr><td>${esc(r[C.tanggal])}<br>${esc(r[C.jam])}</td><td>${esc(r[C.noKa])}</td><td>${esc(r[C.trainset])}</td><td>${esc(r[C.posisi])}</td><td>${esc(r[C.lokasi])}</td><td><b>${esc(String(r[C.kategori]).split(":")[0])}</b><br>${esc(r[C.uraian])}</td><td>${esc(r[C.dampak])}</td><td>${esc(r[C.telat])}'</td><td>${esc(r[C.dipo])}</td><td>${esc(r[C.status])}</td></tr>`).join("");renderDatabase()}
function renderDatabase(){const tb=$("#dbTbody");if(!tb)return;const q=$("#dbCari")?.value.toLowerCase()||"",st=$("#dbFilterStatus")?.value||"",dp=$("#dbFilterDipo")?.value||"",kat=$("#dbFilterKategori")?.value||"";const rows=DATA.filter(r=>(!st||r[C.status]===st)&&(!dp||r[C.dipo]===dp)&&(!kat||String(r[C.kategori]).split(":")[0]===kat)&&(!q||Object.values(r).join(" ").toLowerCase().includes(q)));$("#dbStatTotal")?.textContent=rows.length;$("#dbStatOpen")?.textContent=rows.filter(r=>r[C.status]!=="Selesai").length;$("#dbStatSelesai")?.textContent=rows.filter(r=>r[C.status]==="Selesai").length;$("#dbStatMenit")?.textContent=rows.reduce((a,r)=>a+(Number(r[C.telat])||0),0);$("#dbCountLabel")?.textContent=`${rows.length} rekaman`;tb.innerHTML=rows.map((r,i)=>`<tr ${userRole==="admin"?'data-row="'+i+'" class="clickable"':''}><td>${i+1}</td><td>${esc(r[C.tanggal])}</td><td>${esc(r[C.jam])}</td><td>${esc(r[C.noKa])}</td><td>${esc(r[C.trainset])}</td><td>${esc(r[C.sf])}</td><td>${esc(r[C.posisi])}</td><td>${esc(r[C.lokasi])}</td><td>${esc(String(r[C.kategori]).split(":")[0])}</td><td>${esc(r[C.uraian])}</td><td>${esc(r[C.dampak])}</td><td>${esc(r[C.telat])}'</td><td>${esc(r[C.dipo])}</td><td>${esc(r[C.status])}</td><td>${esc(r[C.pelapor])}</td></tr>`).join("");if(userRole==="admin")tb.querySelectorAll("tr[data-row]").forEach(tr=>tr.addEventListener("click",()=>openDrawer(rows[Number(tr.dataset.row)]))) }
function bind(){["#btnBaru","#btnBaruDb"].forEach(id=>$(id)?.addEventListener("click",()=>openDrawer()));$("#btnTutup")?.addEventListener("click",closeDrawer);$("#btnBatal")?.addEventListener("click",closeDrawer);$("#tirai")?.addEventListener("click",closeDrawer);$("#btnSimpan")?.addEventListener("click",simpan);$("#btnHapus")?.addEventListener("click",()=>{const r=DATA.find(x=>x[C.id]===sunting);if(r)hapus(r)});$("#btnMuat")?.addEventListener("click",()=>muatData());["#fCari","#fBulan","#fKategori","#fDipo","#fStatus","#dbCari","#dbFilterStatus","#dbFilterDipo","#dbFilterKategori"].forEach(id=>{const e=$(id);if(e)e.addEventListener("input",renderAll);if(e)e.addEventListener("change",renderAll)});document.querySelectorAll(".sidebar-nav .nav-item").forEach(n=>n.addEventListener("click",()=>{document.querySelectorAll(".sidebar-nav .nav-item").forEach(x=>x.classList.remove("aktif"));n.classList.add("aktif");document.querySelectorAll(".view").forEach(v=>v.classList.remove("aktif"));const v=$("#view"+n.dataset.view.charAt(0).toUpperCase()+n.dataset.view.slice(1));v?.classList.add("aktif");if(n.dataset.view==="database")renderDatabase()}));$("#menuToggle")?.addEventListener("click",()=>{$("#sidebar")?.classList.toggle("buka");$("#sidebarOverlay")?.classList.toggle("buka")});$("#sidebarOverlay")?.addEventListener("click",()=>{$("#sidebar")?.classList.remove("buka");$("#sidebarOverlay")?.classList.remove("buka")})}
async function muatData(full=false){populate();if(full){await window.__loadOnce?.()}else{try{const r=await apiRead();if(r?.success){DATA=(r.data||[]).map(fromApi);sessionStorage.setItem("gsdata",JSON.stringify(DATA));renderAll()}}catch(e){toast("Google Sheets gagal dibaca; periksa endpoint API/CORS")}}}
window.addEventListener("DOMContentLoaded",async()=>{loginScreenInit();bind();populate();if(loadSession())showDashboard();else showLogin();});
window.__loadOnce=async()=>{try{const r=await apiRead();if(r?.success){DATA=(r.data||[]).map(fromApi);sessionStorage.setItem("gsdata",JSON.stringify(DATA));renderAll()}else throw new Error(r?.error||"API error")}catch(e){try{DATA=JSON.parse(sessionStorage.getItem("gsdata")||"[]")}catch{DATA=[]}renderAll();toast(DATA.length?"Google Sheets gagal dibaca; cache terakhir ditampilkan":"Google Sheets gagal dibaca")}};
})();
