(()=>{
const API_URL="https://script.google.com/macros/s/AKfycbwAA7Z4FnjQPllYt-_w7d6NQ7HGkVBSGHZqNlUjNNvB_B03yvAMyBhIHevd2qGoOJA/exec";
const META="__META__";
const C={id:"ID",tanggal:"Tanggal",jam:"Jam",noKa:"No KA",relasi:"Relasi",trainset:"Trainset",sf:"SF",posisi:"Posisi Kereta",lokasi:"Lokasi",kategori:"Kategori Gangguan",uraian:"Uraian Gangguan",tindakan:"Tindakan",dampak:"Dampak",telat:"Keterlambatan",dipo:"Dipo",pelapor:"Pelapor",status:"Status",dibuat:"Waktu Input"};
function meta(v){try{v=String(v||"");return v.startsWith(META)?JSON.parse(v.slice(META.length)):{};}catch(e){return {};}}
function pack(d){return META+JSON.stringify({tindakan:d[C.tindakan]||"",telat:d[C.telat]||0,dipo:d[C.dipo]||"",pelapor:d[C.pelapor]||"",status:d[C.status]||"Terbuka",dibuat:d[C.dibuat]||new Date().toISOString()});}
function norm(r){const m=meta(r.keterangan||r.Keterangan),n=Number(r.rowIndex||0);return {[C.id]:"gs-"+n,[C.tanggal]:r["Tanggal"]||"",[C.jam]:r["Jam"]||"",[C.noKa]:r["No KA"]||"",[C.relasi]:r.Relasi||"",[C.trainset]:r.Trainset||"",[C.sf]:r.SF||"",[C.posisi]:r["Posisi Kereta"]||"",[C.lokasi]:r.Lokasi||"",[C.kategori]:r.kategori_gangguan||r["Kategori Gangguan"]||"",[C.uraian]:r.uraian_gangguan||r["Uraian Gangguan"]||"",[C.tindakan]:m.tindakan||"",[C.dampak]:r.dampak||r.Dampak||"",[C.telat]:m.telat||0,[C.dipo]:m.dipo||"",[C.pelapor]:m.pelapor||"",[C.status]:m.status||"Terbuka",[C.dibuat]:m.dibuat||"",_apiRowIndex:n};}
async function read(){const j=await(await fetch(API_URL+"?action=read",{cache:"no-store"})).json();if(!j.success)throw Error(j.error||"Gagal membaca Google Sheets");DATA=(j.data||[]).map(norm);return DATA;}
async function create(d){const q=new URLSearchParams({action:"create",tanggal:d[C.tanggal]||"",jam:d[C.jam]||"",no_ka:d[C.noKa]||"",relasi:d[C.relasi]||"",trainset:d[C.trainset]||"",sf:d[C.sf]||"",posisi_kereta:d[C.posisi]||"",lokasi:d[C.lokasi]||"",kategori_gangguan:d[C.kategori]||"",uraian_gangguan:d[C.uraian]||"",dampak:d[C.dampak]||"",keterangan:pack(d)});const j=await(await fetch(API_URL+"?"+q)).json();if(!j.success)throw Error(j.error||"Gagal menambah data");}
async function update(n,d){const q=new URLSearchParams({action:"update",rowIndex:n,kategori_gangguan:d[C.kategori]||"",uraian_gangguan:d[C.uraian]||"",dampak:d[C.dampak]||"",keterangan:pack(d)});const j=await(await fetch(API_URL+"?"+q)).json();if(!j.success)throw Error(j.error||"Gagal memperbarui data");}
async function del(n){const j=await(await fetch(API_URL+"?action=delete&rowIndex="+n)).json();if(!j.success)throw Error(j.error||"Gagal menghapus data");}
window.simpanData=()=>true;
window.muatData=async()=>{try{return await read();}catch(e){console.error(e);DATA=[];if(typeof beritahu==="function")beritahu(e.message);return DATA;}};
window.simpanLaporan=async()=>{if(userRole!=="admin"){beritahu("Hanya admin yang dapat menyimpan.");return;}const d=ambilForm();if(!d[C.tanggal]||!d[C.noKa]||!d[C.trainset]||!d[C.kategori]){beritahu("Lengkapi Tanggal, Nomor KA, Trainset, dan Kategori gangguan.");return;}try{if(sunting){const r=DATA.find(x=>x[C.id]===sunting);if(!r||!r._apiRowIndex)throw Error("Baris Google Sheets tidak ditemukan.");await update(r._apiRowIndex,d);}else{d[C.dibuat]=new Date().toISOString();await create(d);}await muatData();tutupLaci();isiPenyaring();gambar();renderDatabase();beritahu("Data berhasil disimpan ke Google Sheets.");}catch(e){console.error(e);beritahu(e.message||"Gagal menyimpan data.");}};
window.hapusLaporan=async r=>{if(userRole!=="admin")return;if(!r||!r._apiRowIndex)return;if(!confirm("Hapus laporan "+(r[C.noKa]||"")+" / "+(r[C.trainset]||"")+" dari Google Sheets?\n\nData akan dihapus permanen."))return;try{await del(r._apiRowIndex);await muatData();isiPenyaring();gambar();renderDatabase();beritahu("Data berhasil dihapus dari Google Sheets.");}catch(e){console.error(e);beritahu(e.message||"Gagal menghapus data.");}};
const oldRender=window.renderDatabase;window.renderDatabase=function(){oldRender();if(userRole!=="admin")return;document.querySelectorAll("#dbTbody tr").forEach((tr,i)=>{const rows=typeof dbFiltered==="function"?dbFiltered():[];const r=rows[i];if(!r||tr.querySelector(".aksi-api"))return;const td=document.createElement("td");td.className="aksi-api";td.innerHTML='<button type="button" style="margin-right:4px">Edit</button><button type="button">Hapus</button>';td.children[0].onclick=e=>{e.stopPropagation();bukaLaci(r);};td.children[1].onclick=e=>{e.stopPropagation();hapusLaporan(r);};tr.appendChild(td);});};
window.muat=async()=>{await muatData();const f=(id,a,l)=>{const s=document.getElementById(id);if(s)s.innerHTML='<option value="">'+l+'</option>'+a.map(v=>'<option>'+v+'</option>').join("");};f("iKategori",KATEGORI,"Pilih kategori");f("iDampak",DAMPAK,"Pilih dampak");f("iDipo",DIPO,"Pilih dipo");isiPenyaring();gambar();renderDatabase();};
})();